[project]
name = "structural-mechanics-plots"
version = "0.1.0"
description = "Structural Mechanics Creating Load-Strain Curves"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
]
